server:
  port: 8083
  shutdown: "graceful"

# If you want to use a database then uncomment the `group:, readiness: and include: "db"`
# lines in the health probes and uncomment the datasource section
management:
  endpoint:
    health:
        group:
           readiness:
              include: "db"
        show-details: "always"
  endpoints:
      base-path: /
      exposure:
        include: info # should we have more?

springdoc:
  packagesToScan: uk.gov.hmcts.reform.dev
  writer-with-order-by-keys: true

spring:
  config:
    import: "optional:configtree:/mnt/secrets/test/"
  application:
    name: Manage Cases
  datasource:
#    url: jdbc:postgresql://postgres-container:5432/postgres # for docker-compose
    url: jdbc:postgresql://localhost:5432/postgres # for local testing
    driver-class-name: org.postgresql.Driver
    properties:
      charSet: UTF-8
    hikari:
      minimumIdle: 2
      maximumPoolSize: 10
      idleTimeout: 10000
      #poolName: {to-be-defined}HikariCP
      maxLifetime: 7200000
      connectionTimeout: 30000
    username: postgres
    password: Password
  jpa:
    properties:
      hibernate:
        jdbc:
          lob:
            # silence the 'wall-of-text' - unnecessary exception throw about blob types
            non_contextual_creation: true
        hbm2ddl:
          auto: create-drop
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
